In [1]:
import pandas as d

In [2]:
rainfall = pd.read_excel("C:/Users/matom/Downloads/Masters Dissertation/Analysis/durban_station_rainfall.xlsx")
rainfall

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,PRECTOTCORR,PS,WS10M,WS2M,WD10M,WD2M,RH2M,WS10M_MAX,WS10M_MIN,WS2M_MAX,WS2M_MIN
0,1981,32,24.03,24.78,23.08,1.38,101.52,4.90,4.29,86.7,87.1,82.55,7.09,2.84,6.04,2.59
1,1981,33,25.73,26.27,24.81,2.58,101.30,8.53,7.11,46.7,46.7,83.08,12.36,5.55,10.04,4.78
2,1981,34,26.39,27.16,25.79,7.29,100.90,8.51,7.05,44.6,44.6,86.62,11.05,4.34,9.05,3.69
3,1981,35,25.17,25.87,24.40,0.23,100.88,5.26,4.54,189.5,189.3,82.60,7.72,1.28,6.54,1.13
4,1981,36,24.94,25.62,24.36,10.85,101.31,8.54,7.17,188.9,188.9,79.87,10.60,4.64,8.80,4.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13167,2025,175,21.26,21.99,20.43,0.30,101.72,6.15,5.21,30.6,30.6,68.82,10.22,0.26,8.46,0.26
13168,2025,177,21.64,23.96,19.44,2.25,100.47,7.23,6.08,240.3,242.5,67.36,11.60,2.11,9.55,1.68
13169,2025,178,19.70,20.12,19.18,1.37,101.83,6.82,5.86,199.7,199.6,57.33,9.73,2.06,8.18,1.91
13170,2025,180,21.50,22.84,20.35,0.02,102.32,4.83,4.16,204.5,204.6,59.05,6.86,1.67,5.83,1.54
13171,2025,181,21.17,22.02,20.18,0.09,102.42,6.18,5.21,34.3,34.3,67.13,11.29,0.50,9.28,0.44

In [3]:
rainfall.describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,PRECTOTCORR,PS,WS10M,WS2M,WD10M,WD2M,RH2M,WS10M_MAX,WS10M_MIN,WS2M_MAX,WS2M_MIN
count,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000,13172.000000
mean,2003.144473,181.592013,22.417030,23.334635,21.430100,3.176039,101.522973,6.858476,5.780791,123.041831,122.845103,78.975175,9.744398,3.440018,8.076353,2.971382
std,12.860335,113.225641,2.231121,2.255423,2.317023,7.333483,0.593232,2.365795,1.890629,74.272860,74.134649,6.678727,2.825065,2.455376,2.198994,2.055061
min,1981.000000,1.000000,15.360000,16.000000,12.640000,0.010000,99.540000,1.560000,1.310000,0.100000,0.200000,49.720000,2.390000,0.010000,2.180000,0.020000
25%,1992.000000,77.000000,20.680000,21.610000,19.650000,0.150000,101.100000,5.100000,4.390000,46.800000,46.700000,74.777500,7.700000,1.550000,6.500000,1.360000
50%,2003.000000,178.000000,22.490000,23.430000,21.490000,0.750000,101.470000,6.590000,5.580000,126.650000,126.300000,79.770000,9.640000,2.870000,8.020000,2.540000
75%,2014.000000,288.000000,24.250000,25.130000,23.340000,2.950000,101.900000,8.382500,7.010000,193.500000,193.200000,83.770000,11.600000,4.810000,9.530000,4.180000
max,2025.000000,366.000000,28.440000,32.240000,26.930000,130.850000,103.840000,17.280000,13.820000,359.900000,359.700000,96.040000,23.010000,16.330000,18.270000,13.080000

In [5]:
from sklearn.model_selection import train_test_split

split_index = int(len(rainfall) * 0.8)

train_data = rainfall.iloc[:split_index]
test_data = rainfall.iloc[split_index:]

In [6]:
train_data

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,PRECTOTCORR,PS,WS10M,WS2M,WD10M,WD2M,RH2M,WS10M_MAX,WS10M_MIN,WS2M_MAX,WS2M_MIN
0,1981,32,24.03,24.78,23.08,1.38,101.52,4.90,4.29,86.7,87.1,82.55,7.09,2.84,6.04,2.59
1,1981,33,25.73,26.27,24.81,2.58,101.30,8.53,7.11,46.7,46.7,83.08,12.36,5.55,10.04,4.78
2,1981,34,26.39,27.16,25.79,7.29,100.90,8.51,7.05,44.6,44.6,86.62,11.05,4.34,9.05,3.69
3,1981,35,25.17,25.87,24.40,0.23,100.88,5.26,4.54,189.5,189.3,82.60,7.72,1.28,6.54,1.13
4,1981,36,24.94,25.62,24.36,10.85,101.31,8.54,7.17,188.9,188.9,79.87,10.60,4.64,8.80,4.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10532,2016,365,22.85,23.38,22.06,0.10,101.69,4.55,3.97,71.8,72.6,75.62,6.70,1.22,5.72,1.14
10533,2016,366,24.26,24.96,23.16,0.18,101.25,8.86,7.38,45.7,45.6,84.94,10.24,6.74,8.45,5.76
10534,2017,1,24.78,25.51,24.01,0.17,101.04,7.53,6.28,45.3,45.3,90.04,9.40,5.66,7.77,4.75
10535,2017,2,24.87,25.78,24.12,0.13,100.77,9.89,8.14,41.1,41.0,88.21,12.71,7.55,10.35,6.36
10536,2017,3,24.28,25.17,22.86,11.88,101.17,9.97,8.20,199.2,199.4,85.69,13.08,2.81,10.62,2.48